# Generated by Django 3.2 on 2024-02-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEcommerce', '0004_basketproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
